/**
 * AUTO-GENERATED by /home/z/my-project/scripts/generate_quark_js_services.py.
 *
 * DO NOT EDIT BY HAND. To regenerate, run `npm run generate` (which regens
 * the descriptors in src/gen/) and then run the python script to regenerate
 * this file.
 *
 * Each service class below is a thin wrapper around the typed Connect-RPC
 * client produced by `createClient(<generated descriptor>, transport)`.
 * Every method is fully typed — request shapes come from the generated
 * message types in src/gen/<proto>_pb.ts, and responses are typed the same
 * way. Method names match the proto RPC names (in camelCase) exactly.
 */

import type { QuarkTransport, QuarkCallOptions } from '../transport.ts';
import { ServiceClient } from '../transport.ts';
import { createClient, type Client } from '@connectrpc/connect';

import {
  AuthService as AuthServiceDesc,
  UserService as UserServiceDesc,
  IdentityService as IdentityServiceDesc,
  MFAService as MFAServiceDesc,
  PasskeyService as PasskeyServiceDesc,
  SSOService as SSOServiceDesc,
  OAuthServerService as OAuthServerServiceDesc,
  AdminService as AdminServiceDesc,
  RoleService as RoleServiceDesc,
  PolicyService as PolicyServiceDesc,
} from '../gen/auth_pb.js';
import type {
  AdminCreateCustomOAuthProviderRequest,
  AdminCreateSSOProviderRequest,
  AdminCreateUserRequest,
  AdminDeleteCustomOAuthProviderRequest,
  AdminDeleteFactorRequest,
  AdminDeletePasskeyRequest,
  AdminDeleteSSOProviderRequest,
  AdminDeleteUserRequest,
  AdminGenerateLinkRequest,
  AdminGenerateLinkResponse,
  AdminGetCustomOAuthProviderRequest,
  AdminGetSSOProviderRequest,
  AdminGetUserRequest,
  AdminListAuditLogsRequest,
  AdminListCustomOAuthProvidersRequest,
  AdminListPasskeysRequest,
  AdminListUserFactorsRequest,
  AdminListUsersRequest,
  AdminOAuthClientDeleteRequest,
  AdminOAuthClientGetRequest,
  AdminOAuthClientRegenerateSecretRequest,
  AdminOAuthClientRegisterRequest,
  AdminOAuthClientUpdateRequest,
  AdminUpdateCustomOAuthProviderRequest,
  AdminUpdateFactorRequest,
  AdminUpdateSSOProviderRequest,
  AdminUpdateUserRequest,
  AssignRoleRequest,
  ChallengeFactorRequest,
  ChallengeFactorResponse,
  CreatePolicyRequest,
  CreateRoleRequest,
  CreateUserRequest,
  CustomOAuthProvider,
  DeleteIdentityRequest,
  DeletePasskeyRequest,
  DeletePolicyRequest,
  DeleteRoleRequest,
  DeleteUserRequest,
  EnrollFactorRequest,
  EnrollFactorResponse,
  ExternalProviderCallbackRequest,
  ExternalProviderRedirectRequest,
  Factor,
  GetPolicyRequest,
  GetRoleRequest,
  GetUserRequest,
  GrantPermissionRequest,
  HealthStatus,
  InviteRequest,
  JwkSet,
  LinkIdentityRequest,
  ListAuditLogsResponse,
  ListCustomOAuthProvidersResponse,
  ListFactorsRequest,
  ListFactorsResponse,
  ListIdentitiesRequest,
  ListIdentitiesResponse,
  ListOAuthClientsResponse,
  ListOAuthGrantsResponse,
  ListPasskeysRequest,
  ListPasskeysResponse,
  ListPoliciesRequest,
  ListPoliciesResponse,
  ListRolesRequest,
  ListRolesResponse,
  ListSSOProvidersResponse,
  ListUsersRequest,
  ListUsersResponse,
  LoginRequest,
  LoginResponse,
  LogoutRequest,
  MagicLinkRequest,
  OAuthAuthorization,
  OAuthAuthorizeRequest,
  OAuthClient,
  OAuthClientDynamicRegisterRequest,
  OAuthConsentRequest,
  OAuthGetAuthorizationRequest,
  OAuthTokenRequest,
  OpenIdConfiguration,
  OtpRequest,
  Passkey,
  PasskeyAuthOptionsRequest,
  PasskeyAuthOptionsResponse,
  PasskeyAuthVerifyRequest,
  PasskeyOptionsRequest,
  PasskeyRegOptionsResponse,
  PasskeyRegistrationVerifyRequest,
  Policy,
  ReauthenticateResponse,
  RecoverRequest,
  RedirectResponse,
  RefreshRequest,
  ResendRequest,
  ResendResponse,
  RevokeOAuthGrantRequest,
  RevokePermissionRequest,
  RevokeRoleRequest,
  Role,
  SAMLACSRequest,
  SAMLMetadataResponse,
  SSOProvider,
  SSORedirectRequest,
  Settings,
  SignupRequest,
  SignupResponse,
  TokenRequest,
  TokenResponse,
  UnenrollFactorRequest,
  UpdatePasskeyRequest,
  UpdateRoleRequest,
  UpdateUserRequest,
  User,
  UserInfoResponse,
  VerifyFactorRequest,
  VerifyRequest,
  VerifyResponse,
  VerifyTokenRequest,
  VerifyTokenResponse,
} from '../gen/auth_pb.js';
import type { Empty } from '@bufbuild/protobuf/wkt';

/**
 * `platform.auth.v1.AuthService — authentication entry points` — 19 RPCs.
 *
 * Wraps the generated `AuthService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(AuthServiceDesc, transport.underlying)`.
 */
export class AuthService extends ServiceClient {
  private readonly client: Client<typeof AuthServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(AuthServiceDesc, transport.underlying);
  }

  /** `Login` — request: `LoginRequest`, response: `LoginResponse`. */
  login(
    request: LoginRequest,
    options?: QuarkCallOptions,
  ): Promise<LoginResponse> {
    return this.client.login(request, options);
  }

  /** `Refresh` — request: `RefreshRequest`, response: `LoginResponse`. */
  refresh(
    request: RefreshRequest,
    options?: QuarkCallOptions,
  ): Promise<LoginResponse> {
    return this.client.refresh(request, options);
  }

  /** `Logout` — request: `LogoutRequest`, response: `Empty`. */
  logout(
    request: LogoutRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.logout(request, options);
  }

  /** `VerifyToken` — request: `VerifyTokenRequest`, response: `VerifyTokenResponse`. */
  verifyToken(
    request: VerifyTokenRequest,
    options?: QuarkCallOptions,
  ): Promise<VerifyTokenResponse> {
    return this.client.verifyToken(request, options);
  }

  /** `Signup` — request: `SignupRequest`, response: `SignupResponse`. */
  signup(
    request: SignupRequest,
    options?: QuarkCallOptions,
  ): Promise<SignupResponse> {
    return this.client.signup(request, options);
  }

  /** `Token` — request: `TokenRequest`, response: `TokenResponse`. */
  token(
    request: TokenRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.token(request, options);
  }

  /** `Verify` — request: `VerifyRequest`, response: `VerifyResponse`. */
  verify(
    request: VerifyRequest,
    options?: QuarkCallOptions,
  ): Promise<VerifyResponse> {
    return this.client.verify(request, options);
  }

  /** `MagicLink` — request: `MagicLinkRequest`, response: `Empty`. */
  magicLink(
    request: MagicLinkRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.magicLink(request, options);
  }

  /** `Otp` — request: `OtpRequest`, response: `Empty`. */
  otp(
    request: OtpRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.otp(request, options);
  }

  /** `Recover` — request: `RecoverRequest`, response: `Empty`. */
  recover(
    request: RecoverRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.recover(request, options);
  }

  /** `Resend` — request: `ResendRequest`, response: `ResendResponse`. */
  resend(
    request: ResendRequest,
    options?: QuarkCallOptions,
  ): Promise<ResendResponse> {
    return this.client.resend(request, options);
  }

  /** `Reauthenticate` — input is `Empty`. */
  reauthenticate(options?: QuarkCallOptions): Promise<ReauthenticateResponse> {
    return this.client.reauthenticate({}, options);
  }

  /** `GetSettings` — input is `Empty`. */
  getSettings(options?: QuarkCallOptions): Promise<Settings> {
    return this.client.getSettings({}, options);
  }

  /** `GetJwks` — input is `Empty`. */
  getJwks(options?: QuarkCallOptions): Promise<JwkSet> {
    return this.client.getJwks({}, options);
  }

  /** `GetOpenIdConfiguration` — input is `Empty`. */
  getOpenIdConfiguration(options?: QuarkCallOptions): Promise<OpenIdConfiguration> {
    return this.client.getOpenIdConfiguration({}, options);
  }

  /** `Health` — input is `Empty`. */
  health(options?: QuarkCallOptions): Promise<HealthStatus> {
    return this.client.health({}, options);
  }

  /** `ExternalProviderRedirect` — request: `ExternalProviderRedirectRequest`, response: `RedirectResponse`. */
  externalProviderRedirect(
    request: ExternalProviderRedirectRequest,
    options?: QuarkCallOptions,
  ): Promise<RedirectResponse> {
    return this.client.externalProviderRedirect(request, options);
  }

  /** `ExternalProviderCallback` — request: `ExternalProviderCallbackRequest`, response: `TokenResponse`. */
  externalProviderCallback(
    request: ExternalProviderCallbackRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.externalProviderCallback(request, options);
  }

  /** `Invite` — request: `InviteRequest`, response: `User`. */
  invite(
    request: InviteRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.invite(request, options);
  }
}

/**
 * `platform.auth.v1.UserService — user CRUD + role assignment` — 7 RPCs.
 *
 * Wraps the generated `UserService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(UserServiceDesc, transport.underlying)`.
 */
export class UserService extends ServiceClient {
  private readonly client: Client<typeof UserServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(UserServiceDesc, transport.underlying);
  }

  /** `CreateUser` — request: `CreateUserRequest`, response: `User`. */
  createUser(
    request: CreateUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.createUser(request, options);
  }

  /** `GetUser` — request: `GetUserRequest`, response: `User`. */
  getUser(
    request: GetUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.getUser(request, options);
  }

  /** `ListUsers` — request: `ListUsersRequest`, response: `ListUsersResponse`. */
  listUsers(
    request: ListUsersRequest,
    options?: QuarkCallOptions,
  ): Promise<ListUsersResponse> {
    return this.client.listUsers(request, options);
  }

  /** `UpdateUser` — request: `UpdateUserRequest`, response: `User`. */
  updateUser(
    request: UpdateUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.updateUser(request, options);
  }

  /** `DeleteUser` — request: `DeleteUserRequest`, response: `Empty`. */
  deleteUser(
    request: DeleteUserRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteUser(request, options);
  }

  /** `AssignRole` — request: `AssignRoleRequest`, response: `User`. */
  assignRole(
    request: AssignRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.assignRole(request, options);
  }

  /** `RevokeRole` — request: `RevokeRoleRequest`, response: `User`. */
  revokeRole(
    request: RevokeRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.revokeRole(request, options);
  }
}

/**
 * `platform.auth.v1.IdentityService — linked OAuth identities` — 3 RPCs.
 *
 * Wraps the generated `IdentityService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(IdentityServiceDesc, transport.underlying)`.
 */
export class IdentityService extends ServiceClient {
  private readonly client: Client<typeof IdentityServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(IdentityServiceDesc, transport.underlying);
  }

  /** `ListIdentities` — request: `ListIdentitiesRequest`, response: `ListIdentitiesResponse`. */
  listIdentities(
    request: ListIdentitiesRequest,
    options?: QuarkCallOptions,
  ): Promise<ListIdentitiesResponse> {
    return this.client.listIdentities(request, options);
  }

  /** `LinkIdentity` — request: `LinkIdentityRequest`, response: `RedirectResponse`. */
  linkIdentity(
    request: LinkIdentityRequest,
    options?: QuarkCallOptions,
  ): Promise<RedirectResponse> {
    return this.client.linkIdentity(request, options);
  }

  /** `DeleteIdentity` — request: `DeleteIdentityRequest`, response: `Empty`. */
  deleteIdentity(
    request: DeleteIdentityRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteIdentity(request, options);
  }
}

/**
 * `platform.auth.v1.MFAService — TOTP/phone/WebAuthn factor enrolment` — 5 RPCs.
 *
 * Wraps the generated `MFAService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(MFAServiceDesc, transport.underlying)`.
 */
export class MFAService extends ServiceClient {
  private readonly client: Client<typeof MFAServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(MFAServiceDesc, transport.underlying);
  }

  /** `EnrollFactor` — request: `EnrollFactorRequest`, response: `EnrollFactorResponse`. */
  enrollFactor(
    request: EnrollFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<EnrollFactorResponse> {
    return this.client.enrollFactor(request, options);
  }

  /** `ChallengeFactor` — request: `ChallengeFactorRequest`, response: `ChallengeFactorResponse`. */
  challengeFactor(
    request: ChallengeFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<ChallengeFactorResponse> {
    return this.client.challengeFactor(request, options);
  }

  /** `VerifyFactor` — request: `VerifyFactorRequest`, response: `Factor`. */
  verifyFactor(
    request: VerifyFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<Factor> {
    return this.client.verifyFactor(request, options);
  }

  /** `UnenrollFactor` — request: `UnenrollFactorRequest`, response: `Factor`. */
  unenrollFactor(
    request: UnenrollFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<Factor> {
    return this.client.unenrollFactor(request, options);
  }

  /** `ListFactors` — request: `ListFactorsRequest`, response: `ListFactorsResponse`. */
  listFactors(
    request: ListFactorsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListFactorsResponse> {
    return this.client.listFactors(request, options);
  }
}

/**
 * `platform.auth.v1.PasskeyService — WebAuthn passkey management` — 7 RPCs.
 *
 * Wraps the generated `PasskeyService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(PasskeyServiceDesc, transport.underlying)`.
 */
export class PasskeyService extends ServiceClient {
  private readonly client: Client<typeof PasskeyServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(PasskeyServiceDesc, transport.underlying);
  }

  /** `PasskeyAuthenticationOptions` — request: `PasskeyAuthOptionsRequest`, response: `PasskeyAuthOptionsResponse`. */
  passkeyAuthenticationOptions(
    request: PasskeyAuthOptionsRequest,
    options?: QuarkCallOptions,
  ): Promise<PasskeyAuthOptionsResponse> {
    return this.client.passkeyAuthenticationOptions(request, options);
  }

  /** `PasskeyAuthenticationVerify` — request: `PasskeyAuthVerifyRequest`, response: `TokenResponse`. */
  passkeyAuthenticationVerify(
    request: PasskeyAuthVerifyRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.passkeyAuthenticationVerify(request, options);
  }

  /** `PasskeyRegistrationOptions` — request: `PasskeyOptionsRequest`, response: `PasskeyRegOptionsResponse`. */
  passkeyRegistrationOptions(
    request: PasskeyOptionsRequest,
    options?: QuarkCallOptions,
  ): Promise<PasskeyRegOptionsResponse> {
    return this.client.passkeyRegistrationOptions(request, options);
  }

  /** `PasskeyRegistrationVerify` — request: `PasskeyRegistrationVerifyRequest`, response: `Passkey`. */
  passkeyRegistrationVerify(
    request: PasskeyRegistrationVerifyRequest,
    options?: QuarkCallOptions,
  ): Promise<Passkey> {
    return this.client.passkeyRegistrationVerify(request, options);
  }

  /** `ListPasskeys` — request: `ListPasskeysRequest`, response: `ListPasskeysResponse`. */
  listPasskeys(
    request: ListPasskeysRequest,
    options?: QuarkCallOptions,
  ): Promise<ListPasskeysResponse> {
    return this.client.listPasskeys(request, options);
  }

  /** `UpdatePasskey` — request: `UpdatePasskeyRequest`, response: `Passkey`. */
  updatePasskey(
    request: UpdatePasskeyRequest,
    options?: QuarkCallOptions,
  ): Promise<Passkey> {
    return this.client.updatePasskey(request, options);
  }

  /** `DeletePasskey` — request: `DeletePasskeyRequest`, response: `Empty`. */
  deletePasskey(
    request: DeletePasskeyRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deletePasskey(request, options);
  }
}

/**
 * `platform.auth.v1.SSOService — SAML SSO` — 3 RPCs.
 *
 * Wraps the generated `SSOService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(SSOServiceDesc, transport.underlying)`.
 */
export class SSOService extends ServiceClient {
  private readonly client: Client<typeof SSOServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(SSOServiceDesc, transport.underlying);
  }

  /** `SSORedirect` — request: `SSORedirectRequest`, response: `RedirectResponse`. */
  sSORedirect(
    request: SSORedirectRequest,
    options?: QuarkCallOptions,
  ): Promise<RedirectResponse> {
    return this.client.sSORedirect(request, options);
  }

  /** `SAMLACS` — request: `SAMLACSRequest`, response: `TokenResponse`. */
  sAMLACS(
    request: SAMLACSRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.sAMLACS(request, options);
  }

  /** `SAMLMetadata` — input is `Empty`. */
  sAMLMetadata(options?: QuarkCallOptions): Promise<SAMLMetadataResponse> {
    return this.client.sAMLMetadata({}, options);
  }
}

/**
 * `platform.auth.v1.OAuthServerService — Quark as OAuth2/OIDC provider` — 8 RPCs.
 *
 * Wraps the generated `OAuthServerService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(OAuthServerServiceDesc, transport.underlying)`.
 */
export class OAuthServerService extends ServiceClient {
  private readonly client: Client<typeof OAuthServerServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(OAuthServerServiceDesc, transport.underlying);
  }

  /** `OAuthServerAuthorize` — request: `OAuthAuthorizeRequest`, response: `RedirectResponse`. */
  oAuthServerAuthorize(
    request: OAuthAuthorizeRequest,
    options?: QuarkCallOptions,
  ): Promise<RedirectResponse> {
    return this.client.oAuthServerAuthorize(request, options);
  }

  /** `OAuthServerToken` — request: `OAuthTokenRequest`, response: `TokenResponse`. */
  oAuthServerToken(
    request: OAuthTokenRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.oAuthServerToken(request, options);
  }

  /** `OAuthServerUserInfo` — input is `Empty`. */
  oAuthServerUserInfo(options?: QuarkCallOptions): Promise<UserInfoResponse> {
    return this.client.oAuthServerUserInfo({}, options);
  }

  /** `OAuthServerClientDynamicRegister` — request: `OAuthClientDynamicRegisterRequest`, response: `OAuthClient`. */
  oAuthServerClientDynamicRegister(
    request: OAuthClientDynamicRegisterRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthClient> {
    return this.client.oAuthServerClientDynamicRegister(request, options);
  }

  /** `OAuthServerGetAuthorization` — request: `OAuthGetAuthorizationRequest`, response: `OAuthAuthorization`. */
  oAuthServerGetAuthorization(
    request: OAuthGetAuthorizationRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthAuthorization> {
    return this.client.oAuthServerGetAuthorization(request, options);
  }

  /** `OAuthServerConsent` — request: `OAuthConsentRequest`, response: `TokenResponse`. */
  oAuthServerConsent(
    request: OAuthConsentRequest,
    options?: QuarkCallOptions,
  ): Promise<TokenResponse> {
    return this.client.oAuthServerConsent(request, options);
  }

  /** `UserListOAuthGrants` — input is `Empty`. */
  userListOAuthGrants(options?: QuarkCallOptions): Promise<ListOAuthGrantsResponse> {
    return this.client.userListOAuthGrants({}, options);
  }

  /** `UserRevokeOAuthGrant` — request: `RevokeOAuthGrantRequest`, response: `Empty`. */
  userRevokeOAuthGrant(
    request: RevokeOAuthGrantRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.userRevokeOAuthGrant(request, options);
  }
}

/**
 * `platform.auth.v1.AdminService — admin-only operations` — 28 RPCs.
 *
 * Wraps the generated `AdminService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(AdminServiceDesc, transport.underlying)`.
 */
export class AdminService extends ServiceClient {
  private readonly client: Client<typeof AdminServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(AdminServiceDesc, transport.underlying);
  }

  /** `AdminListUsers` — request: `AdminListUsersRequest`, response: `ListUsersResponse`. */
  adminListUsers(
    request: AdminListUsersRequest,
    options?: QuarkCallOptions,
  ): Promise<ListUsersResponse> {
    return this.client.adminListUsers(request, options);
  }

  /** `AdminCreateUser` — request: `AdminCreateUserRequest`, response: `User`. */
  adminCreateUser(
    request: AdminCreateUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.adminCreateUser(request, options);
  }

  /** `AdminGetUser` — request: `AdminGetUserRequest`, response: `User`. */
  adminGetUser(
    request: AdminGetUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.adminGetUser(request, options);
  }

  /** `AdminUpdateUser` — request: `AdminUpdateUserRequest`, response: `User`. */
  adminUpdateUser(
    request: AdminUpdateUserRequest,
    options?: QuarkCallOptions,
  ): Promise<User> {
    return this.client.adminUpdateUser(request, options);
  }

  /** `AdminDeleteUser` — request: `AdminDeleteUserRequest`, response: `Empty`. */
  adminDeleteUser(
    request: AdminDeleteUserRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminDeleteUser(request, options);
  }

  /** `AdminGenerateLink` — request: `AdminGenerateLinkRequest`, response: `AdminGenerateLinkResponse`. */
  adminGenerateLink(
    request: AdminGenerateLinkRequest,
    options?: QuarkCallOptions,
  ): Promise<AdminGenerateLinkResponse> {
    return this.client.adminGenerateLink(request, options);
  }

  /** `AdminListUserFactors` — request: `AdminListUserFactorsRequest`, response: `ListFactorsResponse`. */
  adminListUserFactors(
    request: AdminListUserFactorsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListFactorsResponse> {
    return this.client.adminListUserFactors(request, options);
  }

  /** `AdminDeleteFactor` — request: `AdminDeleteFactorRequest`, response: `Empty`. */
  adminDeleteFactor(
    request: AdminDeleteFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminDeleteFactor(request, options);
  }

  /** `AdminUpdateFactor` — request: `AdminUpdateFactorRequest`, response: `Factor`. */
  adminUpdateFactor(
    request: AdminUpdateFactorRequest,
    options?: QuarkCallOptions,
  ): Promise<Factor> {
    return this.client.adminUpdateFactor(request, options);
  }

  /** `AdminListPasskeys` — request: `AdminListPasskeysRequest`, response: `ListPasskeysResponse`. */
  adminListPasskeys(
    request: AdminListPasskeysRequest,
    options?: QuarkCallOptions,
  ): Promise<ListPasskeysResponse> {
    return this.client.adminListPasskeys(request, options);
  }

  /** `AdminDeletePasskey` — request: `AdminDeletePasskeyRequest`, response: `Empty`. */
  adminDeletePasskey(
    request: AdminDeletePasskeyRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminDeletePasskey(request, options);
  }

  /** `AdminListAuditLogs` — request: `AdminListAuditLogsRequest`, response: `ListAuditLogsResponse`. */
  adminListAuditLogs(
    request: AdminListAuditLogsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListAuditLogsResponse> {
    return this.client.adminListAuditLogs(request, options);
  }

  /** `AdminListSSOProviders` — input is `Empty`. */
  adminListSSOProviders(options?: QuarkCallOptions): Promise<ListSSOProvidersResponse> {
    return this.client.adminListSSOProviders({}, options);
  }

  /** `AdminCreateSSOProvider` — request: `AdminCreateSSOProviderRequest`, response: `SSOProvider`. */
  adminCreateSSOProvider(
    request: AdminCreateSSOProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<SSOProvider> {
    return this.client.adminCreateSSOProvider(request, options);
  }

  /** `AdminGetSSOProvider` — request: `AdminGetSSOProviderRequest`, response: `SSOProvider`. */
  adminGetSSOProvider(
    request: AdminGetSSOProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<SSOProvider> {
    return this.client.adminGetSSOProvider(request, options);
  }

  /** `AdminUpdateSSOProvider` — request: `AdminUpdateSSOProviderRequest`, response: `SSOProvider`. */
  adminUpdateSSOProvider(
    request: AdminUpdateSSOProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<SSOProvider> {
    return this.client.adminUpdateSSOProvider(request, options);
  }

  /** `AdminDeleteSSOProvider` — request: `AdminDeleteSSOProviderRequest`, response: `Empty`. */
  adminDeleteSSOProvider(
    request: AdminDeleteSSOProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminDeleteSSOProvider(request, options);
  }

  /** `AdminOAuthClientRegister` — request: `AdminOAuthClientRegisterRequest`, response: `OAuthClient`. */
  adminOAuthClientRegister(
    request: AdminOAuthClientRegisterRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthClient> {
    return this.client.adminOAuthClientRegister(request, options);
  }

  /** `AdminOAuthClientList` — input is `Empty`. */
  adminOAuthClientList(options?: QuarkCallOptions): Promise<ListOAuthClientsResponse> {
    return this.client.adminOAuthClientList({}, options);
  }

  /** `AdminOAuthClientGet` — request: `AdminOAuthClientGetRequest`, response: `OAuthClient`. */
  adminOAuthClientGet(
    request: AdminOAuthClientGetRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthClient> {
    return this.client.adminOAuthClientGet(request, options);
  }

  /** `AdminOAuthClientUpdate` — request: `AdminOAuthClientUpdateRequest`, response: `OAuthClient`. */
  adminOAuthClientUpdate(
    request: AdminOAuthClientUpdateRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthClient> {
    return this.client.adminOAuthClientUpdate(request, options);
  }

  /** `AdminOAuthClientDelete` — request: `AdminOAuthClientDeleteRequest`, response: `Empty`. */
  adminOAuthClientDelete(
    request: AdminOAuthClientDeleteRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminOAuthClientDelete(request, options);
  }

  /** `AdminOAuthClientRegenerateSecret` — request: `AdminOAuthClientRegenerateSecretRequest`, response: `OAuthClient`. */
  adminOAuthClientRegenerateSecret(
    request: AdminOAuthClientRegenerateSecretRequest,
    options?: QuarkCallOptions,
  ): Promise<OAuthClient> {
    return this.client.adminOAuthClientRegenerateSecret(request, options);
  }

  /** `AdminListCustomOAuthProviders` — request: `AdminListCustomOAuthProvidersRequest`, response: `ListCustomOAuthProvidersResponse`. */
  adminListCustomOAuthProviders(
    request: AdminListCustomOAuthProvidersRequest,
    options?: QuarkCallOptions,
  ): Promise<ListCustomOAuthProvidersResponse> {
    return this.client.adminListCustomOAuthProviders(request, options);
  }

  /** `AdminCreateCustomOAuthProvider` — request: `AdminCreateCustomOAuthProviderRequest`, response: `CustomOAuthProvider`. */
  adminCreateCustomOAuthProvider(
    request: AdminCreateCustomOAuthProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<CustomOAuthProvider> {
    return this.client.adminCreateCustomOAuthProvider(request, options);
  }

  /** `AdminGetCustomOAuthProvider` — request: `AdminGetCustomOAuthProviderRequest`, response: `CustomOAuthProvider`. */
  adminGetCustomOAuthProvider(
    request: AdminGetCustomOAuthProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<CustomOAuthProvider> {
    return this.client.adminGetCustomOAuthProvider(request, options);
  }

  /** `AdminUpdateCustomOAuthProvider` — request: `AdminUpdateCustomOAuthProviderRequest`, response: `CustomOAuthProvider`. */
  adminUpdateCustomOAuthProvider(
    request: AdminUpdateCustomOAuthProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<CustomOAuthProvider> {
    return this.client.adminUpdateCustomOAuthProvider(request, options);
  }

  /** `AdminDeleteCustomOAuthProvider` — request: `AdminDeleteCustomOAuthProviderRequest`, response: `Empty`. */
  adminDeleteCustomOAuthProvider(
    request: AdminDeleteCustomOAuthProviderRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.adminDeleteCustomOAuthProvider(request, options);
  }
}

/**
 * `platform.auth.v1.RoleService — role CRUD + permission grants` — 7 RPCs.
 *
 * Wraps the generated `RoleService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(RoleServiceDesc, transport.underlying)`.
 */
export class RoleService extends ServiceClient {
  private readonly client: Client<typeof RoleServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(RoleServiceDesc, transport.underlying);
  }

  /** `CreateRole` — request: `CreateRoleRequest`, response: `Role`. */
  createRole(
    request: CreateRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<Role> {
    return this.client.createRole(request, options);
  }

  /** `GetRole` — request: `GetRoleRequest`, response: `Role`. */
  getRole(
    request: GetRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<Role> {
    return this.client.getRole(request, options);
  }

  /** `ListRoles` — request: `ListRolesRequest`, response: `ListRolesResponse`. */
  listRoles(
    request: ListRolesRequest,
    options?: QuarkCallOptions,
  ): Promise<ListRolesResponse> {
    return this.client.listRoles(request, options);
  }

  /** `UpdateRole` — request: `UpdateRoleRequest`, response: `Role`. */
  updateRole(
    request: UpdateRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<Role> {
    return this.client.updateRole(request, options);
  }

  /** `DeleteRole` — request: `DeleteRoleRequest`, response: `Empty`. */
  deleteRole(
    request: DeleteRoleRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteRole(request, options);
  }

  /** `GrantPermission` — request: `GrantPermissionRequest`, response: `Role`. */
  grantPermission(
    request: GrantPermissionRequest,
    options?: QuarkCallOptions,
  ): Promise<Role> {
    return this.client.grantPermission(request, options);
  }

  /** `RevokePermission` — request: `RevokePermissionRequest`, response: `Role`. */
  revokePermission(
    request: RevokePermissionRequest,
    options?: QuarkCallOptions,
  ): Promise<Role> {
    return this.client.revokePermission(request, options);
  }
}

/**
 * `platform.auth.v1.PolicyService — RBAC policy CRUD` — 4 RPCs.
 *
 * Wraps the generated `PolicyService` service descriptor from
 * `src/gen/auth_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(PolicyServiceDesc, transport.underlying)`.
 */
export class PolicyService extends ServiceClient {
  private readonly client: Client<typeof PolicyServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(PolicyServiceDesc, transport.underlying);
  }

  /** `CreatePolicy` — request: `CreatePolicyRequest`, response: `Policy`. */
  createPolicy(
    request: CreatePolicyRequest,
    options?: QuarkCallOptions,
  ): Promise<Policy> {
    return this.client.createPolicy(request, options);
  }

  /** `GetPolicy` — request: `GetPolicyRequest`, response: `Policy`. */
  getPolicy(
    request: GetPolicyRequest,
    options?: QuarkCallOptions,
  ): Promise<Policy> {
    return this.client.getPolicy(request, options);
  }

  /** `ListPolicies` — request: `ListPoliciesRequest`, response: `ListPoliciesResponse`. */
  listPolicies(
    request: ListPoliciesRequest,
    options?: QuarkCallOptions,
  ): Promise<ListPoliciesResponse> {
    return this.client.listPolicies(request, options);
  }

  /** `DeletePolicy` — request: `DeletePolicyRequest`, response: `Empty`. */
  deletePolicy(
    request: DeletePolicyRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deletePolicy(request, options);
  }
}


// ─── AuthClient facade ──────────────────────────────────────────────

/**
 * Client for the Quark auth component.

Extends {@link AuthService} so all 19 authentication RPCs (`login`,
`signup`, `token`, `verify`, etc.) are callable directly. The
remaining 9 services are accessed via lazy accessors (`users()`,
`mfa()`, `admin()`, etc.).

NOTE: `organization()` / `project()` / `workspace()` accessors used
to live here but have been migrated to `ServerClient` (see
`src/services/server.ts`) along with the underlying services' move
from `platform.auth.v1` to `platform.server.v1`.

Usage:
```ts
const auth = new AuthClient(transport);
await auth.login({ handle: '…', apiKey: '…' });   // direct — no .auth() needed
await auth.users().createUser({ … });               // via accessor
await auth.mfa().enrollFactor({ … });               // via accessor
```
 */
export class AuthClient extends AuthService {
  private _users?: UserService;
  private _identity?: IdentityService;
  private _mfa?: MFAService;
  private _passkey?: PasskeyService;
  private _sso?: SSOService;
  private _oauthServer?: OAuthServerService;
  private _admin?: AdminService;
  private _role?: RoleService;
  private _policy?: PolicyService;

  /** @internal Constructed by {@link QuarkClientBuilder.build}. */
  constructor(transport: QuarkTransport) {
    super(transport);
  }

  /** The underlying transport (for advanced use). */
  get quarkTransport(): QuarkTransport {
    return this.transport;
  }

  /** platform.auth.v1.UserService — user CRUD + role assignment (7 RPCs). */
  users(): UserService {
    return (this._users ??= new UserService(this.transport));
  }

  /** platform.auth.v1.IdentityService — OAuth identity management (3 RPCs). */
  identity(): IdentityService {
    return (this._identity ??= new IdentityService(this.transport));
  }

  /** platform.auth.v1.MFAService — TOTP/phone/WebAuthn factor enrolment (5 RPCs). */
  mfa(): MFAService {
    return (this._mfa ??= new MFAService(this.transport));
  }

  /** platform.auth.v1.PasskeyService — WebAuthn passkey management (7 RPCs). */
  passkey(): PasskeyService {
    return (this._passkey ??= new PasskeyService(this.transport));
  }

  /** platform.auth.v1.SSOService — SAML SSO (3 RPCs). */
  sso(): SSOService {
    return (this._sso ??= new SSOService(this.transport));
  }

  /** platform.auth.v1.OAuthServerService — Quark as OAuth2/OIDC provider (8 RPCs). */
  oauthServer(): OAuthServerService {
    return (this._oauthServer ??= new OAuthServerService(this.transport));
  }

  /** platform.auth.v1.AdminService — admin-only operations (28 RPCs). */
  admin(): AdminService {
    return (this._admin ??= new AdminService(this.transport));
  }

  /** platform.auth.v1.RoleService — role CRUD + permission grants (7 RPCs). */
  role(): RoleService {
    return (this._role ??= new RoleService(this.transport));
  }

  /** platform.auth.v1.PolicyService — RBAC policy CRUD (4 RPCs). */
  policy(): PolicyService {
    return (this._policy ??= new PolicyService(this.transport));
  }

  /** Release transport resources. */
  async close(): Promise<void> {
    await this.transport.close();
  }
}
