/**
 * AUTO-GENERATED by /home/z/my-project/scripts/generate_quark_js_services.py.
 *
 * DO NOT EDIT BY HAND. To regenerate, run `npm run generate` (which regens
 * the descriptors in src/gen/) and then run the python script to regenerate
 * this file.
 *
 * Each service class below is a thin wrapper around the typed Connect-RPC
 * client produced by `createClient(<generated descriptor>, transport)`.
 * Every method is fully typed — request shapes come from the generated
 * message types in src/gen/<proto>_pb.ts, and responses are typed the same
 * way. Method names match the proto RPC names (in camelCase) exactly.
 */

import type { QuarkTransport, QuarkCallOptions } from '../transport.ts';
import { ServiceClient } from '../transport.ts';
import { createClient, type Client } from '@connectrpc/connect';

import {
  NodeService as NodeServiceDesc,
} from '../gen/node_pb.js';
import type {
  CancelRequest,
  CancelResponse,
  DrainRequest,
  DrainResponse,
  ExecuteRequest,
  ExecuteResponse,
  HealthRequest,
  HealthResponse,
  ReadyRequest,
  ReadyResponse,
  ShutdownRequest,
  ShutdownResponse,
  StatusRequest,
  StatusResponse,
} from '../gen/node_pb.js';

/**
 * `quark.node.v1.NodeService — node execution daemon API` — 7 RPCs.
 *
 * Wraps the generated `NodeService` service descriptor from
 * `src/gen/node_connect.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(NodeServiceDesc, transport.underlying)`.
 */
export class NodeService extends ServiceClient {
  private readonly client: Client<typeof NodeServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(NodeServiceDesc, transport.underlying);
  }

  /** `Execute` — request: `ExecuteRequest`, response: `ExecuteResponse`. */
  execute(
    request: ExecuteRequest,
    options?: QuarkCallOptions,
  ): Promise<ExecuteResponse> {
    return this.client.execute(request, options);
  }

  /** `Cancel` — request: `CancelRequest`, response: `CancelResponse`. */
  cancel(
    request: CancelRequest,
    options?: QuarkCallOptions,
  ): Promise<CancelResponse> {
    return this.client.cancel(request, options);
  }

  /** `Health` — request: `HealthRequest`, response: `HealthResponse`. */
  health(
    request: HealthRequest,
    options?: QuarkCallOptions,
  ): Promise<HealthResponse> {
    return this.client.health(request, options);
  }

  /** `Ready` — request: `ReadyRequest`, response: `ReadyResponse`. */
  ready(
    request: ReadyRequest,
    options?: QuarkCallOptions,
  ): Promise<ReadyResponse> {
    return this.client.ready(request, options);
  }

  /** `Status` — request: `StatusRequest`, response: `StatusResponse`. */
  status(
    request: StatusRequest,
    options?: QuarkCallOptions,
  ): Promise<StatusResponse> {
    return this.client.status(request, options);
  }

  /** `Drain` — request: `DrainRequest`, response: `DrainResponse`. */
  drain(
    request: DrainRequest,
    options?: QuarkCallOptions,
  ): Promise<DrainResponse> {
    return this.client.drain(request, options);
  }

  /** `Shutdown` — request: `ShutdownRequest`, response: `ShutdownResponse`. */
  shutdown(
    request: ShutdownRequest,
    options?: QuarkCallOptions,
  ): Promise<ShutdownResponse> {
    return this.client.shutdown(request, options);
  }
}
