/**
 * AUTO-GENERATED by scripts/generate_quark_js_services.py.
 *
 * DO NOT EDIT BY HAND. To regenerate, run `npm run generate` (which regens
 * the descriptors in src/gen/) and then run the python script to regenerate
 * this file.
 *
 * Each service class below is a thin wrapper around the typed Connect-RPC
 * client produced by `createClient(<generated descriptor>, transport)`.
 * Every method is fully typed — request shapes come from the generated
 * message types in src/gen/<proto>_pb.ts, and responses are typed the same
 * way. Method names match the proto RPC names (in camelCase) exactly.
 */

import type { QuarkTransport, QuarkCallOptions } from '../transport.ts';
import { ServiceClient } from '../transport.ts';
import { createClient, type Client } from '@connectrpc/connect';

import {
  ServerService as ServerServiceDesc,
  OrganizationService as OrganizationServiceDesc,
  ProjectService as ProjectServiceDesc,
  WorkspaceService as WorkspaceServiceDesc,
} from '../gen/server_pb.js';
import type {
  ActivateProjectRequest,
  ActivateRequest,
  ActivateWorkspaceRequest,
  ArchiveProjectRequest,
  ArchiveRequest,
  ArchiveWorkspaceRequest,
  CreateOrganizationRequest,
  CreateProjectRequest,
  CreateWorkspaceRequest,
  DeactivateProjectRequest,
  DeactivateRequest,
  DeactivateWorkspaceRequest,
  DeleteOrganizationRequest,
  DeleteProjectRequest,
  DeleteWorkspaceRequest,
  DeployRequest,
  Deployment,
  GetDeploymentRequest,
  GetOrganizationRequest,
  GetProjectRequest,
  GetWorkspaceRequest,
  ListDeploymentsRequest,
  ListDeploymentsResponse,
  ListOrganizationsRequest,
  ListOrganizationsResponse,
  ListProjectsRequest,
  ListProjectsResponse,
  ListTenantsRequest,
  ListTenantsResponse,
  ListWorkspacesRequest,
  ListWorkspacesResponse,
  Organization,
  Project,
  ProvisionTenantRequest,
  RollbackRequest,
  SystemHealth,
  Tenant,
  UpdateOrganizationRequest,
  UpdateProjectRequest,
  UpdateWorkspaceRequest,
  Workspace,
} from '../gen/server_pb.js';
import type { Empty } from '@bufbuild/protobuf/wkt';

/**
 * `platform.server.v1.ServerService — orchestration, service registry, admin API` — 7 RPCs.
 *
 * Wraps the generated `ServerService` service descriptor from
 * `src/gen/server_pb.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(ServerServiceDesc, transport.underlying)`.
 */
export class ServerService extends ServiceClient {
  private readonly client: Client<typeof ServerServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(ServerServiceDesc, transport.underlying);
  }

  /** `Deploy` — request: `DeployRequest`, response: `Deployment`. */
  deploy(
    request: DeployRequest,
    options?: QuarkCallOptions,
  ): Promise<Deployment> {
    return this.client.deploy(request, options);
  }

  /** `Rollback` — request: `RollbackRequest`, response: `Deployment`. */
  rollback(
    request: RollbackRequest,
    options?: QuarkCallOptions,
  ): Promise<Deployment> {
    return this.client.rollback(request, options);
  }

  /** `GetDeployment` — request: `GetDeploymentRequest`, response: `Deployment`. */
  getDeployment(
    request: GetDeploymentRequest,
    options?: QuarkCallOptions,
  ): Promise<Deployment> {
    return this.client.getDeployment(request, options);
  }

  /** `ListDeployments` — request: `ListDeploymentsRequest`, response: `ListDeploymentsResponse`. */
  listDeployments(
    request: ListDeploymentsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListDeploymentsResponse> {
    return this.client.listDeployments(request, options);
  }

  /** `ProvisionTenant` — request: `ProvisionTenantRequest`, response: `Tenant`. */
  provisionTenant(
    request: ProvisionTenantRequest,
    options?: QuarkCallOptions,
  ): Promise<Tenant> {
    return this.client.provisionTenant(request, options);
  }

  /** `ListTenants` — request: `ListTenantsRequest`, response: `ListTenantsResponse`. */
  listTenants(
    request: ListTenantsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListTenantsResponse> {
    return this.client.listTenants(request, options);
  }

  /** `GetSystemHealth` — input is `Empty`. */
  getSystemHealth(options?: QuarkCallOptions): Promise<SystemHealth> {
    return this.client.getSystemHealth({}, options);
  }
}

/**
 * `platform.server.v1.OrganizationService — organization CRUD + lifecycle` — 8 RPCs.
 *
 * Wraps the generated `OrganizationService` service descriptor from
 * `src/gen/server_pb.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(OrganizationServiceDesc, transport.underlying)`.
 */
export class OrganizationService extends ServiceClient {
  private readonly client: Client<typeof OrganizationServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(OrganizationServiceDesc, transport.underlying);
  }

  /** `CreateOrganization` — request: `CreateOrganizationRequest`, response: `Organization`. */
  createOrganization(
    request: CreateOrganizationRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.createOrganization(request, options);
  }

  /** `GetOrganization` — request: `GetOrganizationRequest`, response: `Organization`. */
  getOrganization(
    request: GetOrganizationRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.getOrganization(request, options);
  }

  /** `ListOrganizations` — request: `ListOrganizationsRequest`, response: `ListOrganizationsResponse`. */
  listOrganizations(
    request: ListOrganizationsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListOrganizationsResponse> {
    return this.client.listOrganizations(request, options);
  }

  /** `UpdateOrganization` — request: `UpdateOrganizationRequest`, response: `Organization`. */
  updateOrganization(
    request: UpdateOrganizationRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.updateOrganization(request, options);
  }

  /** `ActivateOrganization` — request: `ActivateRequest`, response: `Organization`. */
  activateOrganization(
    request: ActivateRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.activateOrganization(request, options);
  }

  /** `DeactivateOrganization` — request: `DeactivateRequest`, response: `Organization`. */
  deactivateOrganization(
    request: DeactivateRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.deactivateOrganization(request, options);
  }

  /** `ArchiveOrganization` — request: `ArchiveRequest`, response: `Organization`. */
  archiveOrganization(
    request: ArchiveRequest,
    options?: QuarkCallOptions,
  ): Promise<Organization> {
    return this.client.archiveOrganization(request, options);
  }

  /** `DeleteOrganization` — request: `DeleteOrganizationRequest`, response: `Empty`. */
  deleteOrganization(
    request: DeleteOrganizationRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteOrganization(request, options);
  }
}

/**
 * `platform.server.v1.ProjectService — project CRUD + lifecycle (org-scoped)` — 8 RPCs.
 *
 * Wraps the generated `ProjectService` service descriptor from
 * `src/gen/server_pb.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(ProjectServiceDesc, transport.underlying)`.
 */
export class ProjectService extends ServiceClient {
  private readonly client: Client<typeof ProjectServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(ProjectServiceDesc, transport.underlying);
  }

  /** `CreateProject` — request: `CreateProjectRequest`, response: `Project`. */
  createProject(
    request: CreateProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.createProject(request, options);
  }

  /** `GetProject` — request: `GetProjectRequest`, response: `Project`. */
  getProject(
    request: GetProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.getProject(request, options);
  }

  /** `ListProjects` — request: `ListProjectsRequest`, response: `ListProjectsResponse`. */
  listProjects(
    request: ListProjectsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListProjectsResponse> {
    return this.client.listProjects(request, options);
  }

  /** `UpdateProject` — request: `UpdateProjectRequest`, response: `Project`. */
  updateProject(
    request: UpdateProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.updateProject(request, options);
  }

  /** `ActivateProject` — request: `ActivateProjectRequest`, response: `Project`. */
  activateProject(
    request: ActivateProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.activateProject(request, options);
  }

  /** `DeactivateProject` — request: `DeactivateProjectRequest`, response: `Project`. */
  deactivateProject(
    request: DeactivateProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.deactivateProject(request, options);
  }

  /** `ArchiveProject` — request: `ArchiveProjectRequest`, response: `Project`. */
  archiveProject(
    request: ArchiveProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Project> {
    return this.client.archiveProject(request, options);
  }

  /** `DeleteProject` — request: `DeleteProjectRequest`, response: `Empty`. */
  deleteProject(
    request: DeleteProjectRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteProject(request, options);
  }
}

/**
 * `platform.server.v1.WorkspaceService — workspace CRUD + lifecycle (project-scoped)` — 8 RPCs.
 *
 * Wraps the generated `WorkspaceService` service descriptor from
 * `src/gen/server_pb.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(WorkspaceServiceDesc, transport.underlying)`.
 */
export class WorkspaceService extends ServiceClient {
  private readonly client: Client<typeof WorkspaceServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(WorkspaceServiceDesc, transport.underlying);
  }

  /** `CreateWorkspace` — request: `CreateWorkspaceRequest`, response: `Workspace`. */
  createWorkspace(
    request: CreateWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.createWorkspace(request, options);
  }

  /** `GetWorkspace` — request: `GetWorkspaceRequest`, response: `Workspace`. */
  getWorkspace(
    request: GetWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.getWorkspace(request, options);
  }

  /** `ListWorkspaces` — request: `ListWorkspacesRequest`, response: `ListWorkspacesResponse`. */
  listWorkspaces(
    request: ListWorkspacesRequest,
    options?: QuarkCallOptions,
  ): Promise<ListWorkspacesResponse> {
    return this.client.listWorkspaces(request, options);
  }

  /** `UpdateWorkspace` — request: `UpdateWorkspaceRequest`, response: `Workspace`. */
  updateWorkspace(
    request: UpdateWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.updateWorkspace(request, options);
  }

  /** `ActivateWorkspace` — request: `ActivateWorkspaceRequest`, response: `Workspace`. */
  activateWorkspace(
    request: ActivateWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.activateWorkspace(request, options);
  }

  /** `DeactivateWorkspace` — request: `DeactivateWorkspaceRequest`, response: `Workspace`. */
  deactivateWorkspace(
    request: DeactivateWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.deactivateWorkspace(request, options);
  }

  /** `ArchiveWorkspace` — request: `ArchiveWorkspaceRequest`, response: `Workspace`. */
  archiveWorkspace(
    request: ArchiveWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Workspace> {
    return this.client.archiveWorkspace(request, options);
  }

  /** `DeleteWorkspace` — request: `DeleteWorkspaceRequest`, response: `Empty`. */
  deleteWorkspace(
    request: DeleteWorkspaceRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteWorkspace(request, options);
  }
}


// ─── ServerClient facade ──────────────────────────────────────────────

/**
 * Client for the Quark server component.

Extends {@link ServerService} so all 8 orchestration RPCs
(`deploy`, `rollback`, `provisionTenant`, …)
are callable directly. The remaining 3 services (organizations /
projects / workspaces) are accessed via lazy accessors.

Usage:
```ts
const server = new ServerClient(transport);
await server.deploy({ versionId: '…', workflowId: '…', input: … });  // direct
await server.organizations().createOrganization({ … });              // via accessor
```
 */
export class ServerClient extends ServerService {
  private _organization?: OrganizationService;
  private _project?: ProjectService;
  private _workspace?: WorkspaceService;

  /** @internal Constructed by {@link QuarkClientBuilder.build}. */
  constructor(transport: QuarkTransport) {
    super(transport);
  }

  /** The underlying transport (for advanced use). */
  get quarkTransport(): QuarkTransport {
    return this.transport;
  }

  /** platform.server.v1.OrganizationService — organization CRUD + lifecycle (8 RPCs). */
  organization(): OrganizationService {
    return (this._organization ??= new OrganizationService(this.transport));
  }

  /** platform.server.v1.ProjectService — project CRUD + lifecycle (8 RPCs). */
  project(): ProjectService {
    return (this._project ??= new ProjectService(this.transport));
  }

  /** platform.server.v1.WorkspaceService — workspace CRUD + lifecycle (8 RPCs). */
  workspace(): WorkspaceService {
    return (this._workspace ??= new WorkspaceService(this.transport));
  }

  /** Release transport resources. */
  async close(): Promise<void> {
    await this.transport.close();
  }
}
