/**
 * AUTO-GENERATED by scripts/generate_quark_js_services.py.
 *
 * DO NOT EDIT BY HAND. To regenerate, run `npm run generate` (which regens
 * the descriptors in src/gen/) and then run the python script to regenerate
 * this file.
 *
 * Each service class below is a thin wrapper around the typed Connect-RPC
 * client produced by `createClient(<generated descriptor>, transport)`.
 * Every method is fully typed — request shapes come from the generated
 * message types in src/gen/<proto>_pb.ts, and responses are typed the same
 * way. Method names match the proto RPC names (in camelCase) exactly.
 */

import type { QuarkTransport, QuarkCallOptions } from '../transport.ts';
import { ServiceClient } from '../transport.ts';
import { createClient, type Client } from '@connectrpc/connect';

import {
  WorkflowService as WorkflowServiceDesc,
} from '../gen/workflow_pb.js';
import type {
  CancelRunRequest,
  CreateWorkflowRequest,
  DeleteWorkflowRequest,
  GetRunRequest,
  GetWorkflowRequest,
  ListRunsRequest,
  ListRunsResponse,
  ListWorkflowsRequest,
  ListWorkflowsResponse,
  Run,
  StartRunRequest,
  UpdateWorkflowRequest,
  Workflow,
} from '../gen/workflow_pb.js';
import type { Empty } from '@bufbuild/protobuf/wkt';

/**
 * `platform.workflow.v1.WorkflowService — workflow + run lifecycle proxy` — 9 RPCs.
 *
 * Wraps the generated `WorkflowService` service descriptor from
 * `src/gen/workflow_pb.ts`. Each method delegates to the
 * typed Connect-RPC client produced by
 * `createClient(WorkflowServiceDesc, transport.underlying)`.
 */
export class WorkflowService extends ServiceClient {
  private readonly client: Client<typeof WorkflowServiceDesc>;

  constructor(transport: QuarkTransport) {
    super(transport);
    this.client = createClient(WorkflowServiceDesc, transport.underlying);
  }

  /** `CreateWorkflow` — request: `CreateWorkflowRequest`, response: `Workflow`. */
  createWorkflow(
    request: CreateWorkflowRequest,
    options?: QuarkCallOptions,
  ): Promise<Workflow> {
    return this.client.createWorkflow(request, options);
  }

  /** `GetWorkflow` — request: `GetWorkflowRequest`, response: `Workflow`. */
  getWorkflow(
    request: GetWorkflowRequest,
    options?: QuarkCallOptions,
  ): Promise<Workflow> {
    return this.client.getWorkflow(request, options);
  }

  /** `ListWorkflows` — request: `ListWorkflowsRequest`, response: `ListWorkflowsResponse`. */
  listWorkflows(
    request: ListWorkflowsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListWorkflowsResponse> {
    return this.client.listWorkflows(request, options);
  }

  /** `UpdateWorkflow` — request: `UpdateWorkflowRequest`, response: `Workflow`. */
  updateWorkflow(
    request: UpdateWorkflowRequest,
    options?: QuarkCallOptions,
  ): Promise<Workflow> {
    return this.client.updateWorkflow(request, options);
  }

  /** `DeleteWorkflow` — request: `DeleteWorkflowRequest`, response: `Empty`. */
  deleteWorkflow(
    request: DeleteWorkflowRequest,
    options?: QuarkCallOptions,
  ): Promise<Empty> {
    return this.client.deleteWorkflow(request, options);
  }

  /** `StartRun` — request: `StartRunRequest`, response: `Run`. */
  startRun(
    request: StartRunRequest,
    options?: QuarkCallOptions,
  ): Promise<Run> {
    return this.client.startRun(request, options);
  }

  /** `GetRun` — request: `GetRunRequest`, response: `Run`. */
  getRun(
    request: GetRunRequest,
    options?: QuarkCallOptions,
  ): Promise<Run> {
    return this.client.getRun(request, options);
  }

  /** `CancelRun` — request: `CancelRunRequest`, response: `Run`. */
  cancelRun(
    request: CancelRunRequest,
    options?: QuarkCallOptions,
  ): Promise<Run> {
    return this.client.cancelRun(request, options);
  }

  /** `ListRuns` — request: `ListRunsRequest`, response: `ListRunsResponse`. */
  listRuns(
    request: ListRunsRequest,
    options?: QuarkCallOptions,
  ): Promise<ListRunsResponse> {
    return this.client.listRuns(request, options);
  }
}
